MODEL:
  # ARCH: Standard_swa
  ARCH: Standard

INPUT:
  SIZE: 
    - 32 
    - 32

TEST:
  BATCH_SIZE: 64
  # BATCH_SIZE: 408

OPTIM:
  LR: 1e-3  # 1e-5 for TTAC

CORRUPTION:
  DATASET: cifar10
  NUM_CLASS: 10
  SEVERITY:
    - 5
  TYPE:
    - motion_blur
    - snow
    - fog
    - shot_noise
    - defocus_blur
    - contrast
    - zoom_blur
    - brightness
    - frost
    - elastic_transform
    - glass_blur
    - gaussian_noise
    - pixelate
    - jpeg_compression
    - impulse_noise