MODEL:
  ARCH: Standard_R50

INPUT:
  SIZE: 
    - 224 
    - 224

TEST:
  BATCH_SIZE: 64

OPTIM:
  LR: 5e-4

CORRUPTION:
  DATASET: imagenet
  NUM_CLASS: 1000
  NUM_EX: 5000
  SEVERITY:
    - 5
  TYPE:
    - motion_blur
    - snow
    - fog
    - shot_noise
    - defocus_blur
    - contrast
    - zoom_blur
    - brightness
    - frost
    - elastic_transform
    - glass_blur
    - gaussian_noise
    - pixelate
    - jpeg_compression
    - impulse_noise
  